### ISSUE TITLE
ImportError: No module named 'httplib'

### ISSUE THREAD

**Issue by zbence** [mishbahr/djangocms-disqus#1]
ImportError: No module named 'httplib'

Thrown when try to run `python manage.py cms check`. My python version is 3.5 and these packeges are installed:
- disqus-python (0.4.2)
- djangocms-disqus (0.1.2)

Anyone met this error before?

**Comment by mishbahr** [comment]
I'll look into this as soon as I can (probably this weekend)

**Comment by zbence** [comment]
Looks like this is a python2 <-> python3 compatibility problem because in python3 the httplib package was renamed. Any support for python3 will be available ?

**Comment by mishbahr** [comment]
Unfortunately the issue is with the disqus python library: `disqus-python`
See https://github.com/disqus/disqus-python/issues/25 and https://github.com/disqus/disqus-python/issues/26

**Comment by mishbahr** [comment]
@zbence Can you try installing the latest `disqus-python` from github?

`pip install git+https://github.com/disqus/disqus-python.git`

**Comment by zbence** [comment]
Pulling the master branch of this repo and the disqus-python solved the problem. Thank you for your advice
