### ISSUE TITLE
ImportError: cannot import name 'patterns'

### ISSUE THREAD

**Issue by marcindbar** [mishbahr/djangocms-disqus#4]
I try to use djangocms-disqus with Django 1.10 and get import error

File "/home/marcin/.virtualenvs/webproject/lib/python3.6/site-packages/djangocms_disqus/cms_plugins.py", line 6, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'

as 'patterns' are removed in Django 1.10. Is there any chance to fix it soon :)?

**Comment by mishbahr** [comment]
I'll fix it this weekend. Thanks

**Comment by marcindbar** [comment]
Thank you, I would be very grateful.
